### ISSUE TITLE
Consider deprecating Cidr trait in favor of inherent methods

### ISSUE THREAD

**Issue by TedDriggs** [stbuehler/rust-cidr#6]
Currently `IpCidr` appears to expose only two methods. A lot of its functionality is in the `Cidr` trait. Having a separate trait requires two imports to access "inherent" functionality, such as getting the network length.

In contrast, `std::net::IpAddr` and the IPv4 and IPv6 address structs expose most of their functionality as inherent methods. This makes a better [documentation experience](https://doc.rust-lang.org/std/net/enum.IpAddr.html) and allows access to that functionality with a single `use`.

# Proposal
Deprecate `Cidr` in favor of the same inherent methods on `IpCidr`, `Ipv4Cidr`, and `Ipv6Cidr`.

**Comment by stbuehler** [comment]
I see your point for easier usage, but I'm certainly not gonna deprecating the traits.

Not quite sure how I'd like to do it - I might try to impl `Defer` to the trait, but I doubt it'll work.

**Comment by TedDriggs** [comment]
I don't think you can `Deref` to a trait, but since the trait impl is already using a macro you might be able to have the macro generate inherent methods and then have the trait bodies call those instead.

**Comment by stbuehler** [comment]
Actually you can `Deref` to a trait and call trait methods even when the trait isn't in scope:

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=55e208f48788f56a6756bdb9112a7473)
```rust
mod foo {
    pub trait Foo {
        fn foo(&self);
    }
    
    pub struct Bar;
    
    impl Foo for Bar {
        fn foo(&self) {
        }
    }
    
    impl std::ops::Deref for Bar {
        type Target = dyn Foo;
        
        fn deref(&self) -> &Self::Target {
            self
        }
    }
}

fn main() {
    let b = foo::Bar;
    b.foo();
}
```

Whether that is a good idea... doesn't matter much, because the `Inet` and `Cidr` traits aren't object safe, so it won't work.

(Telling me what a good idea macros are is not really useful. I obviously already know about macros and how to use them.)

Sadly duplicating the methods also means duplicating ("triplicating"?) the doc strings... that could be theoretically avoided by using even more macros, but I don't think I'll go anywhere near that.

**Comment by stbuehler** [comment]
ab673f45bd053bd488793e77f0c35da785edfa42 now on master.
